In [1]:
import pickle
from pathlib import Path
totalseg_dir = Path("/nfs/data/nii/data1/Analysis/camaret___in_context_segmentation/ANALYSIS_20251122/data/totalseg/")
with open(totalseg_dir / "totalseg_stats.pkl", "rb") as f:
    totalseg_stats = pickle.load(f) # case_id -> {label_id -> (bbox, volume, center)}

In [2]:
# Extract total occurrences and average volume for each label_id
from collections import defaultdict

label_stats = defaultdict(lambda: {"count": 0, "total_volume": 0.0})

for case_id, labels in totalseg_stats.items():
    for label_id, info in labels.items():
        label_stats[label_id]["count"] += 1
        label_stats[label_id]["total_volume"] += float(info["volume"])

# Calculate average volume and create summary
label_summary = {
    label_id: {
        "occurrences": stats["count"],
        "avg_volume": stats["total_volume"] / stats["count"]
    }
    for label_id, stats in label_stats.items()
}

# Display as a sorted DataFrame
import pandas as pd
df_label_stats = pd.DataFrame.from_dict(label_summary, orient="index")
df_label_stats.index.name = "label_id"
df_label_stats = df_label_stats.sort_values("occurrences", ascending=False)
df_label_stats

                   occurrences     avg_volume
label_id
spinal_cord               1183   15882.996619
autochthon_left           1133   84760.713151
autochthon_right          1131   84166.481874
aorta                     1104   55447.712862
esophagus                 1033    8074.079380
...                        ...            ...
vertebrae_C4               250    3465.568000
brain                      249  204927.823293
vertebrae_C3               229    3623.135371
kidney_cyst_left            30   23475.466667
kidney_cyst_right           25   28289.760000

[117 rows x 2 columns]

In [3]:
import sys
sys.path.append("/nfs/norasys/notebooks/camaret/ic_segmentation")
from data.label_ids_totalseg import category_map
category_map

{'esophagus': 'Organs (Abd/Pelvis)',
 'stomach': 'Organs (Abd/Pelvis)',
 'duodenum': 'Organs (Abd/Pelvis)',
 'small_bowel': 'Organs (Abd/Pelvis)',
 'colon': 'Organs (Abd/Pelvis)',
 'liver': 'Organs (Abd/Pelvis)',
 'gallbladder': 'Organs (Abd/Pelvis)',
 'pancreas': 'Organs (Abd/Pelvis)',
 'spleen': 'Organs (Abd/Pelvis)',
 'kidney_left': 'Organs (Abd/Pelvis)',
 'kidney_right': 'Organs (Abd/Pelvis)',
 'urinary_bladder': 'Organs (Abd/Pelvis)',
 'prostate': 'Organs (Abd/Pelvis)',
 'adrenal_gland_right': 'Organs (Abd/Pelvis)',
 'adrenal_gland_left': 'Organs (Abd/Pelvis)',
 'kidney_cyst_left': 'Organs (Abd/Pelvis)',
 'kidney_cyst_right': 'Organs (Abd/Pelvis)',
 'heart': 'Organs (Thorax/Head/Spine)',
 'lung_upper_lobe_left': 'Organs (Thorax/Head/Spine)',
 'lung_lower_lobe_left': 'Organs (Thorax/Head/Spine)',
 'lung_upper_lobe_right': 'Organs (Thorax/Head/Spine)',
 'lung_middle_lobe_right': 'Organs (Thorax/Head/Spine)',
 'lung_lower_lobe_right': 'Organs (Thorax/Head/Spine)',
 'trachea': 'Organs (Thorax/Head/Spine)',
 'thyroid_gland': 'Organs (Thorax/Head/Spine)',
 'brain': 'Organs (Thorax/Head/Spine)',
 'spinal_cord': 'Organs (Thorax/Head/Spine)',
 'atrial_appendage_left': 'Organs (Thorax/Head/Spine)',
 'vertebrae_C7': 'Bones (Spine)',
 'vertebrae_T1': 'Bones (Spine)',
 'vertebrae_T2': 'Bones (Spine)',
 'vertebrae_T3': 'Bones (Spine)',
 'vertebrae_T4': 'Bones (Spine)',
 'vertebrae_T5': 'Bones (Spine)',
 'vertebrae_T6': 'Bones (Spine)',
 'vertebrae_T7': 'Bones (Spine)',
 'vertebrae_T8': 'Bones (Spine)',
 'vertebrae_T9': 'Bones (Spine)',
 'vertebrae_T10': 'Bones (Spine)',
 'vertebrae_T11': 'Bones (Spine)',
 'vertebrae_T12': 'Bones (Spine)',
 'vertebrae_L1': 'Bones (Spine)',
 'vertebrae_L2': 'Bones (Spine)',
 'vertebrae_L3': 'Bones (Spine)',
 'vertebrae_L4': 'Bones (Spine)',
 'vertebrae_L5': 'Bones (Spine)',
 'vertebrae_S1': 'Bones (Spine)',
 'sacrum': 'Bones (Spine)',
 'vertebrae_C1': 'Bones (Spine)',
 'vertebrae_C2': 'Bones (Spine)',
 'vertebrae_C3': 'Bones (Spine)',
 'vertebrae_C4': 'Bones (Spine)',
 'vertebrae_C5': 'Bones (Spine)',
 'vertebrae_C6': 'Bones (Spine)',
 'sternum': 'Bones (Ribs/Sternum)',
 'costal_cartilages': 'Bones (Ribs/Sternum)',
 'rib_left_1': 'Bones (Ribs/Sternum)',
 'rib_left_2': 'Bones (Ribs/Sternum)',
 'rib_left_3': 'Bones (Ribs/Sternum)',
 'rib_left_4': 'Bones (Ribs/Sternum)',
 'rib_left_5': 'Bones (Ribs/Sternum)',
 'rib_left_6': 'Bones (Ribs/Sternum)',
 'rib_left_7': 'Bones (Ribs/Sternum)',
 'rib_left_8': 'Bones (Ribs/Sternum)',
 'rib_left_9': 'Bones (Ribs/Sternum)',
 'rib_left_10': 'Bones (Ribs/Sternum)',
 'rib_left_11': 'Bones (Ribs/Sternum)',
 'rib_right_1': 'Bones (Ribs/Sternum)',
 'rib_right_2': 'Bones (Ribs/Sternum)',
 'rib_right_3': 'Bones (Ribs/Sternum)',
 'rib_right_4': 'Bones (Ribs/Sternum)',
 'rib_right_5': 'Bones (Ribs/Sternum)',
 'rib_right_6': 'Bones (Ribs/Sternum)',
 'rib_right_7': 'Bones (Ribs/Sternum)',
 'rib_right_8': 'Bones (Ribs/Sternum)',
 'rib_right_9': 'Bones (Ribs/Sternum)',
 'rib_right_10': 'Bones (Ribs/Sternum)',
 'rib_right_11': 'Bones (Ribs/Sternum)',
 'rib_left_12': 'Bones (Ribs/Sternum)',
 'rib_right_12': 'Bones (Ribs/Sternum)',
 'skull': 'Bones (Limbs/Shoulder/Pelvis)',
 'clavicula_left': 'Bones (Limbs/Shoulder/Pelvis)',
 'clavicula_right': 'Bones (Limbs/Shoulder/Pelvis)',
 'scapula_left': 'Bones (Limbs/Shoulder/Pelvis)',
 'scapula_right': 'Bones (Limbs/Shoulder/Pelvis)',
 'humerus_left': 'Bones (Limbs/Shoulder/Pelvis)',
 'humerus_right': 'Bones (Limbs/Shoulder/Pelvis)',
 'hip_left': 'Bones (Limbs/Shoulder/Pelvis)',
 'hip_right': 'Bones (Limbs/Shoulder/Pelvis)',
 'femur_left': 'Bones (Limbs/Shoulder/Pelvis)',
 'femur_right': 'Bones (Limbs/Shoulder/Pelvis)',
 'autochthon_left': 'Muscles',
 'autochthon_right': 'Muscles',
 'iliopsoas_left': 'Muscles',
 'iliopsoas_right': 'Muscles',
 'gluteus_maximus_left': 'Muscles',
 'gluteus_maximus_right': 'Muscles',
 'gluteus_medius_left': 'Muscles',
 'gluteus_medius_right': 'Muscles',
 'gluteus_minimus_left': 'Muscles',
 'gluteus_minimus_right': 'Muscles',
 'aorta': 'Vessels',
 'iliac_artery_left': 'Vessels',
 'iliac_artery_right': 'Vessels',
 'subclavian_artery_left': 'Vessels',
 'subclavian_artery_right': 'Vessels',
 'superior_vena_cava': 'Vessels',
 'inferior_vena_cava': 'Vessels',
 'brachiocephalic_vein_left': 'Vessels',
 'iliac_vena_left': 'Vessels',
 'iliac_vena_right': 'Vessels',
 'pulmonary_vein': 'Vessels',
 'portal_vein_and_splenic_vein': 'Vessels',
 'common_carotid_artery_left': 'Vessels',
 'common_carotid_artery_right': 'Vessels',
 'brachiocephalic_vein_right': 'Vessels',
 'brachiocephalic_trunk': 'Vessels'}

In [ ]:
## add category names to the DataFrame
df_label_stats["category"] = df_label_stats.index.map(category_map)
df_label_stats = df_label_stats[["category", "occurrences", "avg_volume"]]

Index([], dtype='object', name='label_id')

Label split heuristic : paired-block

Rule: Always keep Left/Right pairs together (e.g., both Kidneys in Val, both Adrenals in Train).

Reason: If the model sees the left organ during training, segmentation of the right organ becomes a trivial symmetry task rather than a test of true generalization.

Regional Contiguity (No Serial Leakage):

Rule: For serial structures like Ribs and Vertebrae, split by anatomical region (e.g., Upper Ribs vs. Lower Ribs) rather than interleaving them (e.g., Rib 1 vs. Rib 2).

Reason: Adjacent structures share nearly identical local shapes. Splitting by region forces the model to generalize to different shapes (e.g., floating ribs vs. attached ribs) rather than just interpolating between neighbors.

Volume-Weighted Balancing:

Rule: Counter-weight massive organs against each other (e.g., Liver in Val vs. Lungs in Train) to equalize total occurrences and voxel volume.

Reason: This prevents one split from being dominated by "easy" large targets while the other is full of "hard" small targets, ensuring the difficulty is comparable.

In [12]:

split_dict = {
    "train": [
        "spinal_cord",  # Added
        "rib_left_1", "rib_right_1", "rib_left_2", "rib_right_2", 
        "rib_left_3", "rib_right_3", "rib_left_4", "rib_right_4", 
        "rib_left_5", "rib_right_5", "rib_left_6", "rib_right_6",
        "lung_upper_lobe_left", "lung_upper_lobe_right", 
        "lung_lower_lobe_left", "lung_lower_lobe_right", 
        "lung_middle_lobe_right", 
        "heart", "trachea", "thyroid_gland", 
        "stomach", "spleen", "pancreas", "gallbladder", 
        "adrenal_gland_left", "adrenal_gland_right", 
        "clavicula_left", "clavicula_right", 
        "scapula_left", "scapula_right", 
        "humerus_left", "humerus_right", 
        "hip_left", "hip_right", 
        "gluteus_maximus_left", "gluteus_maximus_right", 
        "gluteus_medius_left", "gluteus_medius_right", 
        "gluteus_minimus_left", "gluteus_minimus_right", 
        "aorta", "pulmonary_vein", 
        "subclavian_artery_left", "subclavian_artery_right", 
        "common_carotid_artery_left", "common_carotid_artery_right", 
        "vertebrae_C1", "vertebrae_C2", "vertebrae_C3", "vertebrae_C4", 
        "vertebrae_C5", "vertebrae_C6", "vertebrae_C7", 
        "vertebrae_T1", "vertebrae_T2", "vertebrae_T3", "vertebrae_T4", "vertebrae_T5"
    ],
    "val": [
        "vertebrae_S1", # Added
        "rib_left_7", "rib_right_7", "rib_left_8", "rib_right_8", 
        "rib_left_9", "rib_right_9", "rib_left_10", "rib_right_10", 
        "rib_left_11", "rib_right_11", "rib_left_12", "rib_right_12", 
        "sternum", "costal_cartilages", 
        "liver", 
        "kidney_left", "kidney_right", "kidney_cyst_left", "kidney_cyst_right", 
        "colon", "small_bowel", "duodenum", 
        "urinary_bladder", "prostate", "esophagus", 
        "brain", "atrial_appendage_left", 
        "femur_left", "femur_right", "skull", 
        "iliopsoas_left", "iliopsoas_right", 
        "autochthon_left", "autochthon_right", 
        "inferior_vena_cava", "superior_vena_cava", 
        "portal_vein_and_splenic_vein", 
        "iliac_artery_left", "iliac_artery_right", 
        "iliac_vena_left", "iliac_vena_right", 
        "brachiocephalic_vein_left", "brachiocephalic_vein_right", "brachiocephalic_trunk", 
        "vertebrae_T6", "vertebrae_T7", "vertebrae_T8", "vertebrae_T9", 
        "vertebrae_T10", "vertebrae_T11", "vertebrae_T12", 
        "vertebrae_L1", "vertebrae_L2", "vertebrae_L3", "vertebrae_L4", "vertebrae_L5", 
        "sacrum"
    ]
}
# add split info to the DataFrame
def get_split(label_id):
    for split, labels in split_dict.items():
        if label_id in labels:
            return split
    return "unknown"

df_label_stats["split"] = df_label_stats.index.map(get_split)
df_label_stats = df_label_stats[["category", "occurrences", "avg_volume", "split"]]
df_label_stats.to_csv(totalseg_dir / "label_stats.csv")

In [14]:
df_label_stats[df_label_stats["split"] == "train"].sort_values("occurrences", ascending=False)

,category,occurrences,avg_volume,split
label_id,,,,
spinal_cord,Organs (Thorax/Head/Spine),1183,15882.996619,train
aorta,Vessels,1104,55447.712862,train
lung_upper_lobe_left,Organs (Thorax/Head/Spine),1024,222578.120117,train
lung_lower_lobe_left,Organs (Thorax/Head/Spine),1006,198957.605368,train
lung_lower_lobe_right,Organs (Thorax/Head/Spine),991,228107.647830,train
heart,Organs (Thorax/Head/Spine),924,147998.127706,train
rib_left_6,Bones (Ribs/Sternum),909,4891.446645,train
stomach,Organs (Abd/Pelvis),905,84356.187845,train
lung_upper_lobe_right,Organs (Thorax/Head/Spine),894,209568.449664,train
spleen,Organs (Abd/Pelvis),886,63364.875847,train
lung_middle_lobe_right,Organs (Thorax/Head/Spine),881,97875.156640,train
rib_right_6,Bones (Ribs/Sternum),869,5047.527043,train
rib_left_5,Bones (Ribs/Sternum),868,4390.672811,train
rib_right_5,Bones (Ribs/Sternum),840,4594.960714,train
adrenal_gland_right,Organs (Abd/Pelvis),827,1048.899637,train
pancreas,Organs (Abd/Pelvis),811,17176.720099,train
scapula_left,Bones (Limbs/Shoulder/Pelvis),809,23186.943140,train
rib_left_4,Bones (Ribs/Sternum),806,4145.274194,train
adrenal_gland_left,Organs (Abd/Pelvis),800,1199.748750,train
pulmonary_vein,Vessels,793,6019.416141,train
trachea,Organs (Thorax/Head/Spine),792,9750.941919,train
rib_right_4,Bones (Ribs/Sternum),787,4182.161372,train
scapula_right,Bones (Limbs/Shoulder/Pelvis),786,23539.212468,train
rib_left_3,Bones (Ribs/Sternum),773,3524.139715,train
rib_right_3,Bones (Ribs/Sternum),766,3463.933420,train
common_carotid_artery_left,Vessels,753,1397.277556,train
rib_left_2,Bones (Ribs/Sternum),752,3165.152926,train
rib_right_2,Bones (Ribs/Sternum),751,3144.800266,train
subclavian_artery_left,Vessels,751,2414.596538,train
vertebrae_T3,Bones (Spine),742,6304.711590,train
rib_left_1,Bones (Ribs/Sternum),742,2800.495957,train
vertebrae_T4,Bones (Spine),738,6633.334688,train
rib_right_1,Bones (Ribs/Sternum),738,2818.883469,train
vertebrae_T5,Bones (Spine),733,6902.763984,train
subclavian_artery_right,Vessels,731,2204.313269,train
clavicula_left,Bones (Limbs/Shoulder/Pelvis),727,6610.177442,train
vertebrae_T2,Bones (Spine),724,6623.769337,train
clavicula_right,Bones (Limbs/Shoulder/Pelvis),723,6995.015214,train
common_carotid_artery_right,Vessels,721,928.276006,train
vertebrae_T1,Bones (Spine),704,6488.806818,train
thyroid_gland,Organs (Thorax/Head/Spine),704,4103.613636,train
vertebrae_C7,Bones (Spine),691,3777.746744,train
gallbladder,Organs (Abd/Pelvis),655,6653.470229,train
hip_left,Bones (Limbs/Shoulder/Pelvis),646,96016.820433,train
hip_right,Bones (Limbs/Shoulder/Pelvis),639,96081.758998,train
gluteus_medius_left,Muscles,625,63771.120000,train
humerus_right,Bones (Limbs/Shoulder/Pelvis),618,16550.388350,train
humerus_left,Bones (Limbs/Shoulder/Pelvis),614,15661.965798,train
gluteus_medius_right,Muscles,613,63119.309951,train
gluteus_maximus_left,Muscles,595,131553.670588,train
gluteus_maximus_right,Muscles,594,136316.255892,train
gluteus_minimus_left,Muscles,578,16693.892734,train
gluteus_minimus_right,Muscles,569,17989.084359,train
vertebrae_C6,Bones (Spine),556,2359.807554,train
vertebrae_C5,Bones (Spine),349,2824.730659,train
vertebrae_C2,Bones (Spine),253,4588.324111,train
vertebrae_C1,Bones (Spine),250,3866.256000,train
vertebrae_C4,Bones (Spine),250,3465.568000,train
vertebrae_C3,Bones (Spine),229,3623.135371,train

In [15]:
df_label_stats[df_label_stats["split"] == "val"].sort_values("occurrences", ascending=False)

,category,occurrences,avg_volume,split
label_id,,,,
autochthon_left,Muscles,1133,84760.713151,val
autochthon_right,Muscles,1131,84166.481874,val
esophagus,Organs (Abd/Pelvis),1033,8074.079380,val
costal_cartilages,Bones (Ribs/Sternum),1017,33461.928220,val
inferior_vena_cava,Vessels,977,17155.522006,val
sternum,Bones (Ribs/Sternum),959,14121.300313,val
liver,Organs (Abd/Pelvis),939,392488.880724,val
colon,Organs (Abd/Pelvis),913,155435.303395,val
rib_left_7,Bones (Ribs/Sternum),891,5314.369248,val
rib_left_9,Bones (Ribs/Sternum),890,4431.049438,val
rib_left_8,Bones (Ribs/Sternum),888,4694.040541,val
vertebrae_T11,Bones (Spine),887,11791.255919,val
rib_left_10,Bones (Ribs/Sternum),880,3733.434091,val
vertebrae_T10,Bones (Spine),877,10747.156214,val
vertebrae_T12,Bones (Spine),871,12752.241102,val
rib_right_10,Bones (Ribs/Sternum),866,3778.769053,val
rib_right_11,Bones (Ribs/Sternum),866,2355.942263,val
rib_right_8,Bones (Ribs/Sternum),860,5012.416279,val
rib_right_9,Bones (Ribs/Sternum),860,4687.497674,val
rib_left_11,Bones (Ribs/Sternum),857,2442.283547,val
rib_right_7,Bones (Ribs/Sternum),851,5555.027027,val
vertebrae_T9,Bones (Spine),849,9207.590106,val
iliopsoas_right,Muscles,842,51886.945368,val
iliopsoas_left,Muscles,836,54901.779904,val
portal_vein_and_splenic_vein,Vessels,830,5985.227711,val
small_bowel,Organs (Abd/Pelvis),811,199832.496917,val
kidney_left,Organs (Abd/Pelvis),802,35374.632170,val
vertebrae_L1,Bones (Spine),801,14196.722846,val
vertebrae_T8,Bones (Spine),796,8195.232412,val
rib_left_12,Bones (Ribs/Sternum),790,1005.005063,val
rib_right_12,Bones (Ribs/Sternum),785,986.428025,val
kidney_right,Organs (Abd/Pelvis),782,35655.152174,val
superior_vena_cava,Vessels,777,5567.118404,val
duodenum,Organs (Abd/Pelvis),768,13457.016927,val
vertebrae_T7,Bones (Spine),745,7671.187919,val
brachiocephalic_vein_right,Vessels,735,1745.413605,val
vertebrae_T6,Bones (Spine),732,6981.310109,val
brachiocephalic_vein_left,Vessels,731,3466.503420,val
brachiocephalic_trunk,Vessels,731,1640.192886,val
vertebrae_L2,Bones (Spine),712,15277.518258,val
atrial_appendage_left,Organs (Thorax/Head/Spine),673,2174.742942,val
iliac_artery_left,Vessels,651,4934.239631,val
vertebrae_L3,Bones (Spine),645,17634.716279,val
iliac_artery_right,Vessels,644,4973.793478,val
iliac_vena_left,Vessels,636,8305.033019,val
vertebrae_L4,Bones (Spine),636,17891.836478,val
iliac_vena_right,Vessels,629,6880.257552,val
vertebrae_L5,Bones (Spine),619,17854.004847,val
sacrum,Bones (Spine),618,48168.145631,val
vertebrae_S1,Bones (Spine),597,13758.237856,val
urinary_bladder,Organs (Abd/Pelvis),571,54574.213660,val
femur_left,Bones (Limbs/Shoulder/Pelvis),566,55048.328622,val
femur_right,Bones (Limbs/Shoulder/Pelvis),557,54017.653501,val
skull,Bones (Limbs/Shoulder/Pelvis),473,81618.879493,val
prostate,Organs (Abd/Pelvis),345,7643.373913,val
brain,Organs (Thorax/Head/Spine),249,204927.823293,val
kidney_cyst_left,Organs (Abd/Pelvis),30,23475.466667,val
kidney_cyst_right,Organs (Abd/Pelvis),25,28289.760000,val